### ISSUE TITLE
Application menu

### ISSUE THREAD

**Issue by raeballz** [ConnorNicolINPS/BasicTextEditorWPF#11]
Currently, the application menu is empty. We should probably discuss some way of pulling in templates using this menu, instead of using a combo box possibly.

**Comment by ConnorNicolINPS** [comment]
going to do  some investigation word

**Comment by ConnorNicolINPS** [comment]
Application menu is not user friendly or workable- does not easily allow customization 
- no click handlers for buttons
- menu opens in strange ways - going off of the main window
  - if you set flow to "Right to left" the menu stays in the window but all buttons stay to the right of the      menu
    not workable
