### ISSUE TITLE
Insert Tag Broken

### ISSUE THREAD

**Issue by raeballz** [ConnorNicolINPS/BasicTextEditorWPF#5]
Inserting a tag will crash the program.

**Comment by ConnorNicolINPS** [comment]
fixed the original bug! 
noticed that app crashes if you press one of the buttons without selecting an item from the corresponding combo-boxes 
going to fix this at the same time

**Comment by raeballz** [comment]
@ConnorNicolINPS  Ahh right, cheers! I raised bug #15, if you want to take it?

**Comment by ConnorNicolINPS** [comment]
fix associated with #18
